kind: pipeline # 定义一个管道
type: docker # 当前管道的类型
name: build # 当前管道的名称

steps:
  - name: test
    image: golang
    commands:
      - go test

  - name: build
    image: golang
    commands:
      - go build
