kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/src

#clone:
#  disable: true

steps:
  - name: build
    image: golang:latest
    pull: if-not-exists
    depends_on: [clone]
    settings:
      use_cache: true
    environment:
      GO111MODULE: on
      GOPROXY: "https://goproxy.cn,direct"
    volumes:
      - name: go_mod
        path: /drone/src/
      - name: run_docker
        path: /var/run/docker.sock
    commands:
      - pwd # 查看当前目录
      - ls .
#      - git clone -v git@github.com:DanielZSY/DroneDemo.git dronedemo
      - ls

  - name: deploy
    image: golang:latest
    pull: if-not-exists
    depends_on: [build]
    settings:
      repo: danielzsy/serviceapi
      use_cache: true
      username:
        from_secret: dockername
      password:
        from_secret: dockerpwd
    volumes:
      - name: go_mod
        path: /drone/src/
      - name: run_docker
        path: /var/run/docker.sock
    commands:
      - pwd # 查看当前目录
      - ls

volumes:
  - name: go_mod
    host:
      path: /data/go
  - name: run_docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push